/*
 * Simplified Main Method (Java 25+)
 * - This is a simplified form of the main method introduced in modern Java versions.
 * - It allows programs to be written with less boilerplate, improving readability and focus.
 *
 * Characteristics:
 * - Uses an implicit class generated by the compiler.
 * - Does not require the "public static" modifiers.
 * - Does not require command-line arguments declared.
 *
 * Implicit Class
 * - The compiler automatically creates a class to host this method.
 * - Because the class is implicit, it is not possible to declare a package.
 * - This form is intended for simple programs, examples, and learning scenarios.
 *
 * Usage Notes:
 * - Best suited for didactic purposes, experiments, and small examples.
 * - Not recommended for large or structured applications.
 * - This guide uses the simplified main to reduce boilerplate and keep the focus on the language concepts being
 *   demonstrated.
 */
void main() {
    IO.println("Hello World");
}