/*
Project Structure
- This document explains the standard structure of a Java project, including source roots, resource paths, test
  separation, and output directories.
- A well-defined project structure allows IDEs and build tools to correctly compile, test, package, and run Java
  applications in a predictable and reproducible way.

Overview
- Java projects follow a conventional directory layout that separates source code, resources, tests, and generated
  artifacts.
- These conventions are recognized by build tools (Maven, Gradle) and IDEs, enabling automation of compilation,
  testing, and packaging without manual configuration.
- Although layouts may vary, the structure described here represents the most common and widely adopted standard.

Source Roots
- A source root is a directory that contains Java source code files (".java").
- Files located under source roots are compiled by the Java compiler into ".class" files.
- Package declarations inside source files define the directory structure of the compiled output.
- Typical example:
  - "src/main/java": production source code
- Source roots are:
  - Included at compile time
  - Excluded from the runtime classpath after compilation (only ".class" files remain)

Resource Paths
- Resource paths contain non-code files required by the application at runtime.
- These files are not compiled; they are copied as-is to the output directory.
- Resources are made available on the runtime classpath and can be accessed via the ClassLoader.
- Common use cases include:
  - Configuration files
  - SQL scripts
  - Templates
  - Static assets
- Typical example:
  - "src/main/resources"

Test Source Roots
- Test source roots contain Java code used exclusively for testing.
- Test code is compiled separately from production code.
- Tests typically depend on production classes, but not the other way around.
- Typical example:
  - "src/test/java"
- This separation allows:
  - Independent compilation and execution of tests
  - Clear boundaries between production and test logic

Test Resource Paths
- Test resource paths contain non-code files used only during testing.
- These resources are available on the classpath when running tests, but are excluded from production artifacts.
- Common examples:
  - Test-specific configuration files
  - Sample input data
  - Mock resources
- Typical example:
  - "src/test/resources"

Output Directories
- Output directories store generated artifacts produced by the build process.
- This includes:
  - Compiled ".class" files
  - Copied resource files
  - Generated metadata
- The directory structure mirrors package and resource layouts.
- Common output directories:
  - "bin" or "out" (IDE-managed projects)
  - "target" (Maven)
  - "build" (Gradle)

Project Structure Example
my-project/
|- src/
|  |- main/
|  |  |- java/                     // Production source root
|  |  |  |- com/example/modulea/
|  |  |     |- MyClassA.java
|  |  |- resources/                // Production resource root
|  |- test/
|     |- java/                     // Test source root
|     |  |- com/example/modulea/
|     |     |- MyClassATest.java
|     |- resources/                // Test resource root
|- out/                            // Build output directory

Other Common Directories
- src/main/webapp:
  - Used in web applications for static web resources such as HTML, JSP, JSF, and configuration files.
- generated / target/generated-sources:
  - Contains source code generated by annotation processors or build tools.
- target / build/libs:
  - Output directories for compiled artifacts and packaged JARs.
  - Maven stores JARs in "target/", Gradle in "build/libs/".
  - JAR files typically include compiled classes, resources, and the META-INF/manifest file.
- docs:
  - Stores project documentation, README files, and generated Javadoc.
- scripts:
  - Contains scripts for build, deployment, migration, or automation tasks.

Summary
- A consistent project structure is essential for build automation and tooling support.
- Source code, resources, and tests are clearly separated.
- Build outputs are isolated from source directories.
- These conventions improve maintainability, scalability, and team collaboration.
*/
void main() {}