/*
 * Records
 * - This section explains what records are in Java and their purpose as concise, immutable data carriers.
 *
 * Overview
 * - Records are a special type of class introduced to model immutable data.
 * - Declared using the "record" keyword.
 * - Automatically generate:
 *   - A canonical constructor
 *   - Getters for all components (without the "get" prefix, not following JavaBeans naming)
 *   - "equals()", "hashCode()", and "toString()" methods
 * - Fields in records are called "components" and are implicitly "private" and "final".
 *
 * Key Characteristics
 * - Immutable by default: once created, the component values cannot be changed.
 * - Ideal for data carrier classes such as DTOs, value objects, or simple aggregates.
 * - Compact syntax reduces boilerplate while providing standard methods automatically.
 * - Records cannot extend other classes (they implicitly extend "java.lang.Record") but can implement interfaces.
 *
 * Usage
 * - Use records for simple, immutable objects that primarily hold data.
 * - Avoid using records when mutable state, inheritance, or complex behavior is required.
 * - Provides a clean, concise way to create classes that focus on data rather than behavior.
 */

/*
 * Record Declaration
 * - This example demonstrates the declaration of a record named "Person".
 * - The record defines two fields (components): "name" and "age".
 * - These fields are automatically final and initialized via the canonical constructor generated by the record.
 * - Records can also define additional methods, such as the "greet" method shown below.
 */
public record Person(String name, int age) {
    // Instance method
    public void sayHello() {
        IO.println(String.format("Hello, my name is %s, and I am %d years old", name, age));
    }

    // Static Method
    public static void greet() {
        IO.println("Hello from Person record!");
    }
}

/*
 * Usage Example
 * - Demonstrates creating instances of the "Person" record and using both auto-generated accessors and custom methods.
 * - Access record fields using their auto-generated accessor methods (name() and age()).
 * - Call custom methods like "greet()" to add behavior to the record.
 */
void main() {
    // Creating a Person instance
    Person person = new Person("Alice", 30);

    // Calling property methods to access the fields (modification are not allowed since Records are immutable)
    IO.println(person.name()); // Output: Alice
    IO.println(person.age());  // Output: 25

    // Calling behavioral methods to perform actions
    person.sayHello(); // Output: Hello, my name is Alice, and I am 30 years old.

    // Static methods are also called from the record class itself.
    Person.greet(); // Output: Hello from Person record!
}